from django.core.management.base import BaseCommand
from core.models import Word

class Command(BaseCommand):
    help = 'Populates the database with Top 200 Russian vocabulary (Translated)'

    def handle(self, *args, **kwargs):
        # Transliteration Table
        trans_map = {
            'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'ye', 'ё': 'yo',
            'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm',
            'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u',
            'ф': 'f', 'х': 'kh', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch',
            'ъ': '', 'ы': 'y', 'ь': "'", 'э': 'e', 'ю': 'yu', 'я': 'ya'
        }

        def transliterate(text):
            res = []
            for char in text.lower():
                res.append(trans_map.get(char, char))
            return "".join(res).capitalize()

        # Data: Russian, French, Original POS (verb/other)
        raw_data = [
            ("и", "et", "conj"),
            ("в", "dans/en", "prep"),
            ("не", "ne pas", "part"),
            ("он", "il", "pron"),
            ("на", "sur", "prep"),
            ("я", "je", "pron"),
            ("что", "que/quoi", "pron"),
            ("тот", "ce/celui-là", "adj"),
            ("быть", "être", "verb"),
            ("с", "avec", "prep"),
            ("а", "et/mais", "conj"),
            ("весь", "tout", "pron"),
            ("это", "ce/ça", "pron"),
            ("как", "comment", "adv"),
            ("она", "elle", "pron"),
            ("по", "par/selon", "prep"),
            ("но", "mais", "conj"),
            ("они", "ils", "pron"),
            ("к", "vers", "prep"),
            ("у", "chez/près de", "prep"),
            ("ты", "tu", "pron"),
            ("из", "de (origine)", "prep"),
            ("мы", "nous", "pron"),
            ("за", "derrière/pour", "prep"),
            ("вы", "vous", "pron"),
            ("так", "ainsi/si", "adv"),
            ("же", "donc/même", "part"),
            ("от", "de (provenance)", "prep"),
            ("сказать", "dire", "verb"),
            ("этот", "ce/cet", "pron"),
            ("который", "lequel/qui", "pron"),
            ("мочь", "pouvoir", "verb"),
            ("человек", "homme/personne", "noun"),
            ("о", "au sujet de", "prep"),
            ("один", "un/seul", "num"),
            ("ещё", "encore", "adv"),
            ("бы", "(conditionnel)", "part"),
            ("такой", "tel/si", "pron"),
            ("только", "seulement", "adv"),
            ("себя", "soi-même", "pron"),
            ("своё", "le sien", "pron"),
            ("какой", "quel", "pron"),
            ("когда", "quand", "adv"),
            ("уже", "déjà", "adv"),
            ("для", "pour", "prep"),
            ("вот", "voici/voilà", "part"),
            ("кто", "qui", "pron"),
            ("да", "oui", "part"),
            ("говорить", "parler", "verb"),
            ("год", "année", "noun"),
            ("знать", "savoir", "verb"),
            ("мой", "mon", "pron"),
            ("до", "jusqu'à", "prep"),
            ("или", "ou", "conj"),
            ("если", "si", "conj"),
            ("время", "temps", "noun"),
            ("рука", "main/bras", "noun"),
            ("нет", "non", "part"),
            ("самый", "le plus", "adj"),
            ("ни", "ni", "part"),
            ("стать", "devenir", "verb"),
            ("большой", "grand", "adj"),
            ("даже", "même", "part"),
            ("другой", "autre", "adj"),
            ("наш", "notre", "pron"),
            ("свой", "son propre", "pron"),
            ("ну", "eh bien", "part"),
            ("под", "sous", "prep"),
            ("где", "où", "adv"),
            ("дело", "affaire/chose", "noun"),
            ("есть", "manger / être", "verb"),
            ("сам", "soi-même", "pron"),
            ("раз", "fois", "noun"),
            ("чтобы", "pour que", "conj"),
            ("два", "deux", "num"),
            ("там", "là-bas", "adv"),
            ("чем", "que (comparaison)", "conj"),
            ("глаз", "œil", "noun"),
            ("жизнь", "vie", "noun"),
            ("первый", "premier", "adj"),
            ("день", "jour", "noun"),
            ("тут", "ici", "adv"),
            ("во", "dans", "prep"),
            ("ничто", "rien", "pron"),
            ("потом", "ensuite", "adv"),
            ("очень", "très", "adv"),
            ("со", "avec", "prep"),
            ("хотеть", "vouloir", "verb"),
            ("ли", "si (question)", "part"),
            ("при", "près de/lors de", "prep"),
            ("голова", "tête", "noun"),
            ("надо", "il faut", "verb"),
            ("без", "sans", "prep"),
            ("видеть", "voir", "verb"),
            ("идти", "aller", "verb"),
            ("теперь", "maintenant", "adv"),
            ("тоже", "aussi", "adv"),
            ("стоять", "être debout", "verb"),
            ("друг", "ami", "noun"),
            ("дом", "maison", "noun"),
            ("сейчас", "maintenant", "adv"),
            ("можно", "c'est possible", "pred"),
            ("после", "après", "prep"),
            ("слово", "mot", "noun"),
            ("здесь", "ici", "adv"),
            ("думать", "penser", "verb"),
            ("место", "lieu", "noun"),
            ("спросить", "demander", "verb"),
            ("через", "à travers", "prep"),
            ("лицо", "visage", "noun"),
            ("тогда", "alors", "adv"),
            ("ведь", "en effet", "conj"),
            ("хороший", "bon", "adj"),
            ("каждый", "chaque", "adj"),
            ("новый", "nouveau", "adj"),
            ("жить", "vivre", "verb"),
            ("должный", "dû/nécessaire", "adj"),
            ("смотреть", "regarder", "verb"),
            ("почему", "pourquoi", "adv"),
            ("потому", "c'est pourquoi", "adv"),
            ("сторона", "côté", "noun"),
            ("просто", "simplement", "adv"),
            ("нога", "jambe/pied", "noun"),
            ("сидеть", "être assis", "verb"),
            ("понять", "comprendre", "verb"),
            ("иметь", "avoir", "verb"),
            ("конечный", "final", "adj"),
            ("делать", "faire", "verb"),
            ("вдруг", "soudain", "adv"),
            ("над", "au-dessus", "prep"),
            ("взять", "prendre", "verb"),
            ("никто", "personne", "pron"),
            ("сделать", "faire (perfectif)", "verb"),
            ("дверь", "porte", "noun"),
            ("перед", "devant", "prep"),
            ("нужный", "nécessaire", "adj"),
            ("понимать", "comprendre (imparfait)", "verb"),
            ("казаться", "sembler", "verb"),
            ("работа", "travail", "noun"),
            ("три", "trois", "num"),
            ("ваш", "votre", "pron"),
            ("уж", "déjà/vraiment", "part"),
            ("земля", "terre", "noun"),
            ("конец", "fin", "noun"),
            ("несколько", "plusieurs", "adv"),
            ("час", "heure", "noun"),
            ("голос", "voix", "noun"),
            ("город", "ville", "noun"),
            ("последний", "dernier", "adj"),
            ("пока", "pour l'instant", "adv"),
            ("хорошо", "bien", "adv"),
            ("давать", "donner", "verb"),
            ("вода", "eau", "noun"),
            ("более", "plus", "adv"),
            ("хотя", "bien que", "conj"),
            ("всегда", "toujours", "adv"),
            ("второй", "deuxième", "adj"),
            ("куда", "où (direction)", "adv"),
            ("пойти", "aller (perfectif)", "verb"),
            ("стол", "table", "noun"),
            ("ребёнок", "enfant", "noun"),
            ("увидеть", "voir (perfectif)", "verb"),
            ("сила", "force", "noun"),
            ("отец", "père", "noun"),
            ("женщина", "femme", "noun"),
            ("машина", "voiture", "noun"),
            ("случай", "cas", "noun"),
            ("ночь", "nuit", "noun"),
            ("сразу", "aussitôt", "adv"),
            ("мир", "monde/paix", "noun"),
            ("совсем", "tout à fait", "adv"),
            ("остаться", "rester", "verb"),
            ("об", "au sujet de", "prep"),
            ("вид", "vue/aspect", "noun"),
            ("выйти", "sortir", "verb"),
            ("дать", "donner (perfectif)", "verb"),
            ("работать", "travailler", "verb"),
            ("любить", "aimer", "verb"),
            ("старый", "vieux", "adj"),
            ("почти", "presque", "adv"),
            ("ряд", "rangée", "noun"),
            ("оказаться", "s'avérer", "verb"),
            ("начало", "début", "noun"),
            ("твой", "ton", "pron"),
            ("вопрос", "question", "noun"),
            ("много", "beaucoup", "adv"),
            ("война", "guerre", "noun"),
            ("снова", "à nouveau", "adv"),
            ("ответить", "répondre", "verb"),
            ("между", "entre", "prep"),
            ("подумать", "penser (perfectif)", "verb"),
            ("опять", "encore", "adv"),
            ("белый", "blanc", "adj"),
            ("деньги", "argent", "noun"),
            ("значить", "signifier", "verb"),
            ("про", "à propos de", "prep"),
        ]

        # Reset DB
        Word.objects.all().delete()
        
        batch = []
        for rus, fra, pos in raw_data:
            # Determine category: 'verb' if pos says so, otherwise 'word'
            cat = 'verb' if 'verb' in pos else 'word'
            
            # Auto-transliterate
            trans = transliterate(rus)

            batch.append(Word(
                russian=rus,
                french=fra,
                transliteration=trans,
                category=cat
            ))
        
        Word.objects.bulk_create(batch)
            
        self.stdout.write(self.style.SUCCESS(f'Successfully populated {len(batch)} vocabulary items from Top 200 list'))
