# Generated by Django 6.0 on 2025-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1)),
                ('name', models.CharField(help_text="e.g. 'A', 'Be'", max_length=50)),
                ('transliteration', models.CharField(help_text='Latin equivalent', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Usage notes or pronunciation guide')),
                ('example_word_cyrillic', models.CharField(blank=True, max_length=100)),
                ('example_word_meaning', models.CharField(blank=True, max_length=100)),
                ('is_vowel', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
