# Generated by Django 6.0 on 2025-12-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_letter_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('transliteration', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('word', 'Word'), ('verb', 'Verb')], default='word', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={},
        ),
        migrations.RemoveField(
            model_name='letter',
            name='example_word_cyrillic',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='example_word_meaning',
        ),
        migrations.AddField(
            model_name='letter',
            name='example_word_eng',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='letter',
            name='example_word_rus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='icon',
            field=models.CharField(default='📝', max_length=10),
        ),
        migrations.AlterField(
            model_name='letter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='letter',
            name='transliteration',
            field=models.CharField(max_length=10),
        ),
    ]
