# Generated by Django 6.0 on 2025-12-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_word_alter_lesson_options_alter_letter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
