# Generated by Django 6.0 on 2025-12-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_word_needs_review_userwordprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('word', 'Mot'), ('verb', 'Verbe')], default='word', max_length=10),
        ),
    ]
