# Generated by Django 6.0 on 2025-12-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='target_language',
            field=models.CharField(choices=[('ru', 'Russe'), ('en', 'Anglais')], default='ru', max_length=2),
        ),
        migrations.AddField(
            model_name='word',
            name='target_language',
            field=models.CharField(choices=[('ru', 'Russe'), ('en', 'Anglais')], default='ru', max_length=2),
        ),
    ]
