# Generated by Django 6.0 on 2025-12-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lesson_target_language_word_target_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='core.lesson'),
        ),
    ]
