# Generated by Django 6.0 on 2025-12-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_word_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True, help_text="Phrase d'exemple pour illustrer le mot"),
        ),
    ]
