# Generated by Django 6.0 on 2025-12-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_word_example_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordprogress',
            name='ease_factor',
            field=models.FloatField(default=2.5, help_text='Facteur de facilité'),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='interval',
            field=models.IntegerField(default=1, help_text='Intervalle en jours'),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userwordprogress',
            name='streak',
            field=models.IntegerField(default=0, help_text='Nombre de réussites consécutives'),
        ),
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, help_text='Fichier audio pour la prononciation', null=True, upload_to='audio/words/'),
        ),
    ]
