# Generated by Django 6.0 on 2026-01-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='target_language',
            new_name='language',
        ),
        migrations.AddField(
            model_name='word',
            name='aspect',
            field=models.CharField(choices=[('imp', 'Imperfectif'), ('perf', 'Perfectif'), ('none', 'N/A')], default='none', max_length=4),
        ),
        migrations.AddField(
            model_name='word',
            name='aspect_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_aspect', to='core.word'),
        ),
        migrations.AddField(
            model_name='word',
            name='base_form',
            field=models.CharField(blank=True, help_text='Forme de base (Nominatif/Infinitif)', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='declensions',
            field=models.JSONField(blank=True, default=dict, help_text='Suffixes for cases (Singular/Plural)'),
        ),
        migrations.AddField(
            model_name='word',
            name='past_tense',
            field=models.CharField(blank=True, help_text='Prétérit (pour Anglais)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='russian_accented',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='text_root',
            field=models.CharField(blank=True, help_text='Racine invariante (ex: Машин)', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/words/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('noun', 'Nom'), ('verb', 'Verbe'), ('adj', 'Adjectif'), ('adv', 'Adverbe'), ('part', 'Particule'), ('other', 'Autre')], default='noun', max_length=10),
        ),
        migrations.AlterField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True, help_text="Phrase d'exemple"),
        ),
        migrations.AlterField(
            model_name='word',
            name='russian',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='transliteration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
