# Generated by Django 6.0 on 2026-01-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20260125_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='friendship_category',
            field=models.CharField(choices=[('true', 'Vrai Ami'), ('false', 'Faux Ami'), ('new', 'Nouveau (Inconnu)')], default='new', max_length=5),
        ),
    ]
